extd:
  port: 9111
  emqx:
    host: emqx
    port: 18083
    retry: 5
    timeout: 15s
  pgsql:
    host: pgsql
    port: 5432
    name: postgres
  proc:
    emqx:
      adapter:
        port: 9110
      listener:
        port: 20041
