volumes:
  emqx-data:
    name: emqx-data
    external: true
  pgsql-data:
    name: pgsql-data
    external: true

networks:
  nano:
    driver: bridge

services:
  pgsql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    networks:
      - nano
  emqx:
    image: ghcr.io/blabtm/emqx:latest
    ports:
      - 1883:1883
      - 18083:18083
      - 20041:20041
    environment:
      TZ: Asia/Novosibirsk
      EMQX_API_KEY__BOOTSTRAP_FILE: /opt/emqx/data/secret.conf
    networks:
      - nano
    volumes:
      - emqx-data:/opt/emqx/data
  extd:
    build: .
    environment:
      TZ: Asia/Novosibirsk
    networks:
      - nano
    develop:
      watch:
        - action: rebuild
          path: ./cmd
        - action: rebuild
          path: ./internal
        - action: rebuild
          path: ./pkg
        - action: rebuild
          path: ./srv
        - action: sync+restart
          path: ./config/extd-config.yaml
          target: /etc/extd-config.yaml
        - action: sync+restart
          path: ./config/extd-secret.yaml
          target: /etc/extd-secret.yaml
